###**Module 1**

---

####**1.1**
---

In [ ]:
# Import pandas library
import pandas as pd

#Import the csv file of HUL using 'pd.read_csv()' function into a dataframe.
df = pd.read_csv('/content/HINDUNILVR.csv')
df

         Symbol Series  ... Deliverable Qty  % Dly Qt to Traded Qty
0    HINDUNILVR     EQ  ...          420159                   57.21
1    HINDUNILVR     EQ  ...          669576                   44.53
2    HINDUNILVR     EQ  ...          996054                   49.82
3    HINDUNILVR     EQ  ...          983594                   36.55
4    HINDUNILVR     EQ  ...         1523108                   49.78
..          ...    ...  ...             ...                     ...
490  HINDUNILVR     EQ  ...         1248858                   56.44
491  HINDUNILVR     EQ  ...          849935                   68.36
492  HINDUNILVR     EQ  ...          821111                   68.14
493  HINDUNILVR     EQ  ...          581135                   58.07
494  HINDUNILVR     EQ  ...          653294                   56.30

[495 rows x 15 columns]

In [ ]:
# show the first 5 rows using dataframe.head() method
print("The first 5 rows of the dataframe") 
df.head()

The first 5 rows of the dataframe

       Symbol Series  ... Deliverable Qty  % Dly Qt to Traded Qty
0  HINDUNILVR     EQ  ...          420159                   57.21
1  HINDUNILVR     EQ  ...          669576                   44.53
2  HINDUNILVR     EQ  ...          996054                   49.82
3  HINDUNILVR     EQ  ...          983594                   36.55
4  HINDUNILVR     EQ  ...         1523108                   49.78

[5 rows x 15 columns]

In [ ]:
print("The last 10 rows of the dataframe\n")
df.tail(10)

The last 10 rows of the dataframe

         Symbol Series  ... Deliverable Qty  % Dly Qt to Traded Qty
485  HINDUNILVR     EQ  ...          470100                   60.82
486  HINDUNILVR     EQ  ...          892038                   76.14
487  HINDUNILVR     EQ  ...          486269                   61.26
488  HINDUNILVR     EQ  ...          614638                   42.60
489  HINDUNILVR     EQ  ...         1137685                   47.93
490  HINDUNILVR     EQ  ...         1248858                   56.44
491  HINDUNILVR     EQ  ...          849935                   68.36
492  HINDUNILVR     EQ  ...          821111                   68.14
493  HINDUNILVR     EQ  ...          581135                   58.07
494  HINDUNILVR     EQ  ...          653294                   56.30

[10 rows x 15 columns]

In [ ]:
df.describe()

        Prev Close   Open Price  ...  Deliverable Qty  % Dly Qt to Traded Qty
count   495.000000   495.000000  ...     4.950000e+02              495.000000
mean   1471.880606  1476.030000  ...     8.010867e+05               61.639313
std     246.301360   241.366451  ...     3.867355e+05               11.399872
min     339.000000   981.300000  ...     1.869800e+04               20.390000
25%    1266.725000  1269.700000  ...     5.274245e+05               55.020000
50%    1497.900000  1496.900000  ...     7.525270e+05               63.640000
75%    1697.525000  1698.800000  ...     9.602335e+05               69.405000
max    1860.550000  1865.000000  ...     3.019009e+06              100.000000

[8 rows x 12 columns]

In [ ]:
pip install -U pandas-profiling  
#pandas-profiling generates a report with all the information easily available.

In [ ]:
df.profile_report()

In [ ]:
#To avoid repetitions in the date,remove all the rows where 'Series' column is NOT 'EQ'.
df.drop(df[df['Series']!='EQ'].index,inplace=True)
df

         Symbol Series  ... Deliverable Qty  % Dly Qt to Traded Qty
0    HINDUNILVR     EQ  ...          420159                   57.21
1    HINDUNILVR     EQ  ...          669576                   44.53
2    HINDUNILVR     EQ  ...          996054                   49.82
3    HINDUNILVR     EQ  ...          983594                   36.55
4    HINDUNILVR     EQ  ...         1523108                   49.78
..          ...    ...  ...             ...                     ...
490  HINDUNILVR     EQ  ...         1248858                   56.44
491  HINDUNILVR     EQ  ...          849935                   68.36
492  HINDUNILVR     EQ  ...          821111                   68.14
493  HINDUNILVR     EQ  ...          581135                   58.07
494  HINDUNILVR     EQ  ...          653294                   56.30

[494 rows x 15 columns]

####**1.2**
---

In [ ]:
#Calculate the maximum, minimum and mean price for the last 90 days.

df1=df.tail(90)
print("The mean closing price is ",end='')
print(df1['Close Price'].mean())
print("The max closing price is ",end='')
print(df1['Close Price'].max())
print("The min closing price is ",end='')
print(df1['Close Price'].min())

The mean closing price is 1739.6955555555562
The max closing price is 1839.05
The min closing price is 1659.1

####**1.3**

---

CHANGE THE DATA TYPE OF DATE

In [ ]:
df.dtypes  #Analyse the data types for each column of the dataframe.

Symbol                     object
Series                     object
Date                       object
Prev Close                float64
Open Price                float64
High Price                float64
Low Price                 float64
Last Price                float64
Close Price               float64
Average Price             float64
Total Traded Quantity       int64
Turnover                  float64
No. of Trades               int64
Deliverable Qty             int64
% Dly Qt to Traded Qty    float64
dtype: object

In [ ]:
#Change the date column from 'object' type to 'datetime64(ns)' for future convenience.

df.astype({'Date': 'datetime64[ns]'}).dtypes 
#Changed object type in to datetime64[ns]-pandas

Symbol                            object
Series                            object
Date                      datetime64[ns]
Prev Close                       float64
Open Price                       float64
High Price                       float64
Low Price                        float64
Last Price                       float64
Close Price                      float64
Average Price                    float64
Total Traded Quantity              int64
Turnover                         float64
No. of Trades                      int64
Deliverable Qty                    int64
% Dly Qt to Traded Qty           float64
dtype: object

In [ ]:
import datetime
df['Month'] = pd.DatetimeIndex(df['Date']).month #to extract month from date
df['Year'] = pd.DatetimeIndex(df['Date']).year    #to extract year from the date
df

         Symbol Series         Date  ...  % Dly Qt to Traded Qty  Month  Year
0    HINDUNILVR     EQ  15-May-2017  ...                   57.21      5  2017
1    HINDUNILVR     EQ  16-May-2017  ...                   44.53      5  2017
2    HINDUNILVR     EQ  17-May-2017  ...                   49.82      5  2017
3    HINDUNILVR     EQ  18-May-2017  ...                   36.55      5  2017
4    HINDUNILVR     EQ  19-May-2017  ...                   49.78      5  2017
..          ...    ...          ...  ...                     ...    ...   ...
490  HINDUNILVR     EQ  07-May-2019  ...                   56.44      5  2019
491  HINDUNILVR     EQ  08-May-2019  ...                   68.36      5  2019
492  HINDUNILVR     EQ  09-May-2019  ...                   68.14      5  2019
493  HINDUNILVR     EQ  10-May-2019  ...                   58.07      5  2019
494  HINDUNILVR     EQ  13-May-2019  ...                   56.30      5  2019

[494 rows x 17 columns]

####**1.4**

---

FINDING VWAP VALUES USING GROUPBY

In [ ]:
#calculate the monthwise VWAP (Volume Weighted Average Price ) of the stock.
#( VWAP = sum(price*volume)/sum(volume) )

import numpy as np
print("VWAP VALUES ARE")
df1=df.groupby(['Year','Month']).apply(lambda x: np.average(x['Average Price'],weights=x['Total Traded Quantity']))
df1

VWAP VALUES ARE

Year  Month
2017  5        1025.569944
      6        1095.844702
      7        1144.658512
      8        1184.682921
      9        1223.856432
      10       1232.743488
      11       1266.388182
      12       1321.967076
2018  1        1366.952464
      2        1337.170396
      3        1310.169856
      4        1420.346368
      5        1548.265826
      6        1606.399443
      7        1688.346127
      8        1758.087856
      9        1629.068576
      10       1557.005736
      11       1701.613774
      12       1817.690421
2019  1        1767.988938
      2        1778.590216
      3        1705.427266
      4        1709.590167
      5        1693.838713
dtype: float64

####**1.5**

---

TO FIND AVERAGE PRICE AND PERCENTAGE LOSS/PROFIT :

In [ ]:
'''
a function to calculate the average price over the last N days 
of the stock price data where N is a user defined parameter.
'''

def avg_price1(N):
  df2=df.tail(N)
  print(df2['Close Price'].mean())

In [ ]:
'''
the average price AND the profit/loss percentages over the course of last 
1 week, 2 weeks, 1 month, 3 months, 6 months and 1 year
'''
print("AVERAGE PRICE OVER A WEEK IS ",end="")
avg_price1(7)  #week
print("AVERAGE PRICE OVER 2 WEEKS IS ",end="")
avg_price1(14)  # 2 weekS
print("AVERAGE PRICE OVER 1 MONTH IS ",end="")
avg_price1(30) 
print("AVERAGE PRICE OVER 3 MONTHS IS ",end="")
avg_price1(90) 
print("AVERAGE PRICE OVER 6 MONTHS IS ",end="")
avg_price1(150) 
print("AVERAGE PRICE OVER LAST YEAR IS ",end="")
avg_price1(365)

AVERAGE PRICE OVER A WEEK IS 1691.6928571428573
AVERAGE PRICE OVER 2 WEEKS IS 1717.2357142857143
AVERAGE PRICE OVER 1 MONTH IS 1705.2833333333333
AVERAGE PRICE OVER 3 MONTHS IS 1739.6955555555562
AVERAGE PRICE OVER 6 MONTHS IS 1719.3196666666659
AVERAGE PRICE OVER LAST YEAR IS 1583.9738356164385

In [ ]:
# calculate the profit/loss percentage over the last N days.

def profit_loss(data1,n):
  data=data1.tail(n)
  a=0
  for i in range(0,n-1):
    change = data['Close Price'].iloc[i] - data['Close Price'].iloc[i+1]
    per  = (change*100)/data['Close Price'].iloc[i]
    a=a+per
  if(a>0):
    print('PROFIT %  IS ',end="")
    print(a)
  else:
    a=-a
    print('LOSS % IS ',end="")
    print(a)


print("FOR A WEEK  ",end="")
profit_loss(df,7)
print("FOR 2 WEEKS  ",end="")
profit_loss(df,14)
print("FOR A MONTH  ",end="")
profit_loss(df,30)
print("FOR 3 MONTHS  ",end="")
profit_loss(df,90)
print("FOR 6 MONTHS  ",end="")
profit_loss(df,150)
print("FOR 1 YEAR  ",end="")
profit_loss(df,365)

FOR A WEEK  LOSS % IS 0.5365245224581778
FOR 2 WEEKS  PROFIT %  IS 2.1145997550966587
FOR A MONTH  LOSS % IS 1.3782805605122495
FOR 3 MONTHS  PROFIT %  IS 6.331713630252427
FOR 6 MONTHS  LOSS % IS 4.671708136019253
FOR 1 YEAR  LOSS % IS 31.397945028182793

####**1.6**

---

CREATING A NEW COLUMN USING pct_change()

In [ ]:
'''
column 'Day_Perc_Change' where the values are the daily change in percentages 
i.e. the percentage change between 2 consecutive day's closing prices.
'''
df['Day_Perc_Change']=(df['Close Price'].pct_change()*100)
df

         Symbol Series         Date  ...  Month  Year  Day_Perc_Change
0    HINDUNILVR     EQ  15-May-2017  ...      5  2017              NaN
1    HINDUNILVR     EQ  16-May-2017  ...      5  2017         1.744216
2    HINDUNILVR     EQ  17-May-2017  ...      5  2017         0.899640
3    HINDUNILVR     EQ  18-May-2017  ...      5  2017        -1.897167
4    HINDUNILVR     EQ  19-May-2017  ...      5  2017         1.792477
..          ...    ...          ...  ...    ...   ...              ...
490  HINDUNILVR     EQ  07-May-2019  ...      5  2019         1.713704
491  HINDUNILVR     EQ  08-May-2019  ...      5  2019        -0.518409
492  HINDUNILVR     EQ  09-May-2019  ...      5  2019         0.891218
493  HINDUNILVR     EQ  10-May-2019  ...      5  2019        -0.956713
494  HINDUNILVR     EQ  13-May-2019  ...      5  2019         0.862248

[494 rows x 18 columns]

In [ ]:
df['Day_Perc_Change'].iloc[0]=0   #CHANGE NAN TO ZERO
df

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

         Symbol Series         Date  ...  Month  Year  Day_Perc_Change
0    HINDUNILVR     EQ  15-May-2017  ...      5  2017         0.000000
1    HINDUNILVR     EQ  16-May-2017  ...      5  2017         1.744216
2    HINDUNILVR     EQ  17-May-2017  ...      5  2017         0.899640
3    HINDUNILVR     EQ  18-May-2017  ...      5  2017        -1.897167
4    HINDUNILVR     EQ  19-May-2017  ...      5  2017         1.792477
..          ...    ...          ...  ...    ...   ...              ...
490  HINDUNILVR     EQ  07-May-2019  ...      5  2019         1.713704
491  HINDUNILVR     EQ  08-May-2019  ...      5  2019        -0.518409
492  HINDUNILVR     EQ  09-May-2019  ...      5  2019         0.891218
493  HINDUNILVR     EQ  10-May-2019  ...      5  2019        -0.956713
494  HINDUNILVR     EQ  13-May-2019  ...      5  2019         0.862248

[494 rows x 18 columns]

####**1.7**

---

In [ ]:
#trend column 
'''
Slight or No change' for 'Day_Perc_Change' in between -0.5 and 0.5
'Slight positive'  for 'Day_Perc_Change' in between 0.5 and 1
'Slight negative'  for 'Day_Perc_Change' in between -0.5 and -1
'Positive'  for 'Day_Perc_Change' in between 1 and 3
'Negative'  for 'Day_Perc_Change' in between -1 and -3
'Among top gainers'  for 'Day_Perc_Change' in between 3 and 7
'Among top losers'  for 'Day_Perc_Change' in between -3 and -7
'Bull run'  for 'Day_Perc_Change'  &gt;7
'Bear drop'  for 'Day_Perc_Change'  &lt;-7

'''
df.loc[df['Day_Perc_Change'].between(-0.5,0.5),'Trend'] = 'Slight or No change'
df.loc[df['Day_Perc_Change'].between(0.5,1),'Trend'] = 'Slight positive'
df.loc[df['Day_Perc_Change'].between(-0.5,-1),'Trend'] = 'Slight negative'
df.loc[df['Day_Perc_Change'].between(1,3),'Trend'] = 'positive'
df.loc[df['Day_Perc_Change'].between(-1,-3),'Trend'] = 'negative'
df.loc[df['Day_Perc_Change'].between(3,7),'Trend'] = 'among top gainers'
df.loc[df['Day_Perc_Change'].between(-3,-7),'Trend'] = 'among top losers'
df.loc[df['Day_Perc_Change']>=7,'Trend'] = 'bull run'
df.loc[df['Day_Perc_Change']<=-7,'Trend'] = 'bear drop'
df['Trend'].fillna('Other', inplace=True)

In [ ]:
df.head(10) #print dataframe

       Symbol Series         Date  ...  Year  Day_Perc_Change                Trend
0  HINDUNILVR     EQ  15-May-2017  ...  2017         0.000000  Slight or No change
1  HINDUNILVR     EQ  16-May-2017  ...  2017         1.744216             positive
2  HINDUNILVR     EQ  17-May-2017  ...  2017         0.899640      Slight positive
3  HINDUNILVR     EQ  18-May-2017  ...  2017        -1.897167                Other
4  HINDUNILVR     EQ  19-May-2017  ...  2017         1.792477             positive
5  HINDUNILVR     EQ  22-May-2017  ...  2017         1.051587             positive
6  HINDUNILVR     EQ  23-May-2017  ...  2017         0.608679      Slight positive
7  HINDUNILVR     EQ  24-May-2017  ...  2017         1.292935             positive
8  HINDUNILVR     EQ  25-May-2017  ...  2017         0.520206      Slight positive
9  HINDUNILVR     EQ  26-May-2017  ...  2017        -0.239590  Slight or No change

[10 rows x 19 columns]

####**1.8**

---

to find average of total traded quantity using groupby

In [ ]:
df.groupby(['Trend'])['Total Traded Quantity'].mean()

Trend
Other                  1.407437e+06
Slight or No change    1.201715e+06
Slight positive        1.234634e+06
among top gainers      2.613607e+06
positive               1.405669e+06
Name: Total Traded Quantity, dtype: float64

*To find mean of total traded quantity using groupby*

In [ ]:
df.groupby(['Trend'])['Total Traded Quantity'].median()

Trend
Other                  1216028.0
Slight or No change    1063738.5
Slight positive        1133172.5
among top gainers      2367385.0
positive               1374834.0
Name: Total Traded Quantity, dtype: float64

####**1.9**

---

*SAVE the dataframe with the additional columns computed as a csv file week2.csv.*

In [ ]:
df.to_csv("week2.csv",index=False)
from google.colab import files
files.download("week2.csv")